#! ruby -Ks
# -*- mode:ruby; coding:shift_jis -*-
#
$KCODE='s'
#==============================================================================
#Project Name    : BeatSaber Camera2GUI
#Creation Date   : 2021/03/20
#Copyright       : (c) 2021 rynan4818 (Twitter @rynan4818)
#License         : MIT License
#                  https://github.com/rynan4818/Camera2GUI/blob/main/LICENSE
#Tool            : ActiveScriptRuby(1.8.7-p330)
#                  https://www.artonx.org/data/asr/
#                  FormDesigner Release v2020/06/18
#                  https://github.com/rynan4818/formdesigner
#RubyGems Package: rubygems-update (1.8.21)      https://rubygems.org/
#                  json (1.4.6 x86-mswin32)
#==============================================================================

MAIN_MENU_VERSION_TITLE              = "BeatSaber Camera2 GUI Version"
MAIN_SELF_CREATED_BSDIR_CHK_MES      = "The BeatSaber folder is not set.Please set it up."
MAIN_SELF_CREATED_BSDIR_CHK_TITLE    = "BeatSaber folder is missing."
MODALDLG_SETTING_OK_BTN_NO_DIR_MES   = "I don't have a BeatSaber Folder. Do you want to go back and reconfigure it?"
MODALDLG_SETTING_OK_BTN_NO_DIR_TITLE = "BeatSaber Folder setting error"
SETTING_LOAD_ERROR_NO_SCENE          = "'Scenes.json' file not found."
SETTING_LOAD_ERROR_MES               = "Unable to load the configuration file."
SETTING_LOAD_ERROR_NO_CAMERA         = "There is no 'Cameras' folder."
SETTING_LOAD_ERROR_NO_DEFAULT        = "No default configuration file is available."
UNKNOWN_CAMERA_TYPE_MES              = "This is a non-compliant camera type. Cannot be used"
UNKNOWN_CAMERA_TYPE_TITLE            = "Unknown camera type"
LAYER_CONFLICT_MES                   = "Layer conflict. We will reassign the layers, so please check the order."
LAYER_CONFLICT_TITLE                 = "Layer conflict"
CHARACTER_CHECK_MES                  = "is not a valid character."
CHARACTER_CHECK_TITLE                = "Use of non-text"
MODALDLG_CUSTOM_SCENES_ERR_MES       = "is in conflict. Please rename it."
MODALDLG_CUSTOM_SCENES_ERR_TITLE     = "Conflict"
MAIN_DELETE_MES                      = "Can I delete the selected camera?"
MAIN_DELETE_TITLE                    = "Deletion confirmation"
FILE_TIME_CHECK_MES                  = "The Camera2 configuration file has been updated. Do you want to reload it? (Unsaved settings will be lost.)"
FILE_TIME_CHECK_TITLE                = "Configuration file updated."
MAIN_WSH_ERR                         = "WScript.Shell Error"
MAIN_WSH_ERR_TITLE                   = "WSH run ERROR"
TOOLTIP_CAMERA_NAME                  = "Only single-byte alphanumeric symbols and spaces (ASCII characters).\r\nCharacters that cannot be used in file names \\/:*?\"<>| is not allowed."
TOOLTIP_CAMERA_TYPE                  = "Can be FirstPerson or Positionable (Third person)"
TOOLTIP_FIELD_OF_VIEW                = "Angle of camera coverage"
TOOLTIP_FPS_LIMIT                    = "Maximum Frames to render per second (Normally, 0 is recommended)\r\nPlease read the instructions on the Camera2 wiki before setting it up."
TOOLTIP_RENDER_SCALE                 = "Setting the screen roughness"
TOOLTIP_ANTI_ALIASING                = "Reduces jaggies in curved and diagonal lines in text and images"
TOOLTIP_WORLDCAM_VISIBILITY          = "Defines the visibility of the positionable camera, can be Visible, HiddenWhilePlaying or Hidden"
TOOLTIP_PREVIEW_SIZE                 = "Defines the base size of the ingame preview of what this camera sees (For positionable cameras), can be 0.3 to 3.\r\n(Effective after restarting BeatSaber)"
TOOLTIP_Z_OFFSET                     = "Front-back offset for FirstPerson view"
TOOLTIP_RELOAD                       = "Reload the configuration file. Settings that have not been saved will be lost."
TOOLTIP_ADD                          = "Add a camera. (The default value of the camera to be added will be PositionableDefault.json)"
TOOLTIP_COPY                         = "Copy and add the currently selected camera."
TOOLTIP_DEL                          = "Deletes the currently selected camera."
TOOLTIP_SAVE                         = "Save the current settings."
TOOLTIP_SAVE_APPLY                   = "Save the settings and reflect them in Camera2 (BeatSaber must be running)"
TOOLTIP_CAMERA_LIST                  = "Here is the list of camera settings. From left to right: layer number, camera type, and camera name."
TOOLTIP_UP                           = "Raise the layer of the currently selected camera by one"
TOOLTIP_DOWN                         = "Lower the layer of the currently selected camera by one"
TOOLTIP_BS_FOLDER                    = "Set the installation folder of BeatSaber."
TOOLTIP_TOOLTIP                      = "Display the tooltip (show this description)"
TOOLTIP_JAPANESE                     = "Changes messages and tooltips to Japanese. (Effective after reboot.)\r\n*Characters will be garbled on operating systems with system locales other than SHIFT-JIS."
TOOLTIP_UPDATE_CHECK                 = "This is the time to ignore the file timestamp for the configuration file update check on the Camera2 side.\r\nAfter checking for updates using timestamps, the contents of JSON are also compared, so 0 is usually fine."
TOOLTIP_SEND_TIME                    = "This is the key transmission time for Camera2 update key operation.\r\nIf Camera2 is not updated by Apply, increase the value."
TOOLTIP_WAIT_TIME                    = "This is the waiting time for each command in AutoIT (Windows Automatic Operation Tool).\r\nIf the Apply operation is unstable, increase it. normally, 0 is fine."
TOOLTIP_WALLS                        = "Can be Visible, Transparent or Hidden"
TOOLTIP_NOTES                        = "Can be Visible, Hidden or ForceCustomNotes - The latter makes it so the Camera will show your used custom notes, \r\neven when you configure Custom Notes to only show them in VR."
TOOLTIP_DEBRIS                       = "Visibility of fragments of notes after the cut"
TOOLTIP_CUT_PARTICLES                = "Visibility of particle effects during cutting."
TOOLTIP_AVATAR                       = "Avatar Visibility"
TOOLTIP_UI                           = "Visibility of the user interface, including scores"
TOOLTIP_FLOOR                        = "Floor Visibility"
TOOLTIP_FORCE_UPRIGHT                = "Ignores sideways head tilt making it always upright"
TOOLTIP_PIVOTING_OFFSET              = "Applies the offset in a pivoting fashion (Default) instead of an absolute one (Camera Plus default)"
TOOLTIP_FOLLOW_REPLAY_POSITION       = "If enabled, while watching a replay the first person camera will be attached to the replay position instead of whatever else it would be (HMD / FPFC)"
TOOLTIP_POSITION_SMOOTHING           = "Defines how much smoothing there should be, the lower the number the more smoothing there is"
TOOLTIP_360ENABLED                   = "Makes the camera follow the rotation on 360 maps"
TOOLTIP_ROTATION_SMOOTHING           = "Defines how much smoothing there should be, the lower the number the more smoothing there is"
TOOLTIP_MOVE_WITH_MAP                = "If a Noodle extension map moves / rotates you this camera will follow that movement"
TOOLTIP_AUTO_VISIBLE_WALLS           = "Changes your Wall visibility to Visible if you're playing a Noodle or Mapping Extensions map"
TOOLTIP_AUTO_HIDE_HUD                = "Changes your HUD visibility to false (Hidden) if you're playing a Noodle or Mapping Extensions map"
TOOLTIP_SCENE_MENU                   = "Group 3-2:Show this camera in the menu scene"
TOOLTIP_SCENE_MULTIPLAYER_MENU       = "Group 3-1:Show this camera in the multiplayer menu scene"
TOOLTIP_SCENE_PLAYING                = "Group 2-3:Show this camera in a game scene on a normal map"
TOOLTIP_SCENE_PLAYING_360            = "Group 2-2:Show this camera in a 360-degree map game scene"
TOOLTIP_SCENE_PLAYING_MODMAP         = "Group 2-2:Show this camera in game scenes on Mod maps (Noodle or MappingExtensions extension maps)"
TOOLTIP_SCENE_PLAYING_MULTI          = "Group 2-1:Show this camera in a multiplayer game scene"
TOOLTIP_SCENE_REPLAY                 = "Group 2-1:Show this camera in the replay scene"
TOOLTIP_SCENE_FPFC                   = "Group 1:Show this camera in fpfc mode.\r\n(Set 'fpfc' as the startup option of BeatSaber and start it.)"
TOOLTIP_SCENE_SPECTATING_MULTI       = ""
TOOLTIP_AUTOSWITCH_FROM_CUSTOM       = "Automatically switches the above settings when the game scene changes, even when using a custom scene."
TOOLTIP_CUSTOM_SCENES                = "Custom scene settings (can be set in the in-game menu or by using shortcut keys to switch scenes)"
TOOLTIP_AUTO_APPLY                   = "When a value is changed, it is immediately saved and reflected in Camera2."
TOOLTIP_MOVEMENT_FROM_ORIGIN         = "When true the targetPos and targetRot get overwritten when a movement script is in action"
TOOLTIP_MOVEMENT_ENABLE_IN_MENU      = "Enables movement scripts outside of songs"
TOOLTIP_MOVEMENT_SCRIPT_LIST         = "You can pass a list of movement script names(Without the .json!) here of which a random one will be picked on every map load"
TOOLTIP_CUSTOM_SCENES_LIST           = "List of configured custom scenes.\r\n(From left to right: key bindings (if any), name of custom scene)"
TOOLTIP_CUSTOM_SCENES_SCENE          = "Name of the custom scene (ASCII characters only)"
TOOLTIP_CUSTOM_SCENES_KEY            = "Shortcut keys (can be unconfigured, in which case select them from Mod Settings in the menu on the music screen)"
TOOLTIP_CUSTOM_SCENES_CAMERA         = "Select the camera to display."
TOOLTIP_CUSTOM_SCENES_ADD            = "Add a new custom scene."
TOOLTIP_CUSTOM_SCENES_DEL            = "Deletes the currently selected custom scene."
TOOLTIP_CUSTOM_SCENES_CANCEL         = "Discard the current settings without applying them"
TOOLTIP_CUSTOM_SCENES_OK             = "Apply the current settings. To save, you need to go back to the main menu and save."
TOOLTIP_STEAM                        = "The fpfc startup command for BeatSaber on Steam."
TOOLTIP_OCULUS                       = "The fpfc startup command for BeatSaber for Oculus."
TOOLTIP_FPFC                         = "Command to be executed by fpfc start-up of BeatSaber in the menu.\r\n(With a pre-check that BeatSaber has not been started yet)"
MENU_FPFC_NOCOMMAND_MES              = "There is no setting for the fpfc startup command, please set it in Option Setting."
MENU_FPFC_NOCOMMAND_TITLE            = "There is no fpfc startup command."
MENU_FPFC_EXIST_MES                  = "BeatSaber is running and will not execute.\r\n'#{BEATSABER_WINDOW_NAME}'window title is used to make decisions, so there is a possibility of misidentification"
MENU_FPFC_EXIST_TITLE                = "BeatSaber is running."
JSON_FILE_SAVE_DEL_ERR_MES           = "Unable to delete camera files."
JSON_FILE_SAVE_DEL_ERR_TITLE         = "File delete error"
ALL_JSON_FILE_SAVE_TITLE             = "Saves all current camera and scene settings in a single JSON file"
ALL_JSON_FILE_LOAD_TITLE             = "Load all camera and scene settings from a saved JSON file. To reflect the settings in Camera2, you need to SAVE after reading them."
ALL_JSON_FILE_LOAD_ERR_MES           = "This JSON file cannot be read"
ALL_JSON_FILE_LOAD_ERR_TITLE         = "JSON file error"
TOOLTIP_SETTING_FOLDER               = "This setting is used to save all camera and scene settings in a JSON file, and to fix the folder to be read out."
TOOLTIP_RESET                        = "Reset Target Pos and Rot to 0"
TOOLTIP_POS_AMOUNT                   = "Amount of movement of Target Pos"
TOOLTIP_ROT_AMOUNT                   = "Amount of movement of Target Rot"
TOOLTIP_VIEW_AMOUNT                  = "Amount of movement of View Rect"
TOOLTIP_X_ROTATION_OFFSET            = ""
TOOLTIP_LOCK_SCREEN                  = ""
TOOLTIP_ORTHOGRAPHIC                 = ""
TOOLTIP_FOLLOW_SPECTATOR_PLATTFORM   = ""
TOOLTIP_FAR_Z                        = ""
TOOLTIP_VMC_DESTINATION              = ""
TOOLTIP_VMC_MODE                     = ""
